### creation item
POST http://localhost:3000/films
Content-Type: application/json

{
    "title" : "new film",
    "duration" : 150,
    "budget" : 140000000,
    "link" : "www.wiki.com"
}

### read all film
GET  http://localhost:3000/films